### PR TITLE
Add 'float' mapping to Swagger generator

### PR DESCRIPTION
**Pull request by maxkoryukov**
Add `float` to list of native python types

### CODE REVIEW

**Comment by maxkoryukov** [comment]
I have no idea, why Travis CI didn't send coverage-data with:

> Coverage.py warning: No data was collected.

**Comment by maxkoryukov** [comment]
ping @noirbizarre 
plz, take a look at this amendment.

I am pinging, just to know, that the repo is alive, and it makes sense to wait for merge/decline

**Comment by noirbizarre** [comment]
Hi !
Thanks.
I'll need a testcase, you can add `float` in [this one](https://github.com/noirbizarre/flask-restplus/blob/master/tests/test_swagger.py#L916-L963)

Just so I know, what is your use case ? Most of the time you'll want to have some control on how `float` type is serialized, and to do so there is multiple fields to handle floats: [`FloatField`, `FixedField` and `ArbitraryField`](http://flask-restplus.readthedocs.io/en/stable/api.html#flask_restplus.fields.Float).
But I agree that in some case, it's simply faster to use raw float to prototype.

**Comment by bedge** [comment]
I resubmitted with test case here https://github.com/noirbizarre/flask-restplus/pull/273

**Comment by maxkoryukov** [comment]
I am going to close this in favor of #273, thanks to @bedge ;)

**Pull request closed without merging**
