### PR TITLE
Added ability to override host_url when setting the value for host in…

### PR DESCRIPTION
**Pull request by sharan-karanth**
This fix will allow the client to pass a host url that will be used instead of app.config["SERVER_NAME"] if provided.

Let me know what you think

Sharan

### CODE REVIEW

**Comment by noirbizarre** [comment]
Hi !

Thanks for the contrib, but before merging I need to understand the use case and to discuss if it's the better way of doing it.

With this PR, is the point is being able to give a sandbox URL as host URL in the swagger.json specification (and only in the specifications) ? Is this for everyone who fetch/use the specifications or only for SwaggerUI ?

My point is that if this is only for swagger-ui to use a sanbox instead of the real API, maybe it would be better to implement this at query time with a query string. (ie. swagger.json?host_url=test.api.com) allowing to specify host_url only in your swagger-ui instance.
Some user may want to use your specifications for real use and it will be misleading.

I was working on fixing #41 by properly using the subdomain in blueprint (I need a little bit of time because I never used the subdomain feature it).
But I want to be sure to understand that this is really another use case.

**Comment by sharan-karanth** [comment]
This is a fix for the issue described in issue #103 

In my case, the api will always be in its own subdomain (and Blueprint). And these subdomains will exist in all environments (staging, production).

So, while your recommendation of using host_url as a query parameter would work, I would never want the swagger page to show any other server name as the host since I am initializing the Api with my Blueprint.

Does that make sense?

**Comment by noirbizarre** [comment]
Sorry, I was talking about #103 too.

For me the proper fix would be to really use the blueprint subdomain value instead of having to manually set `host_url`.
subdomain can be dynamic, so the top of the top would be to be able to detect the current subdomain for dynamic subdomains

**Comment by sharan-karanth** [comment]
Yeah. You are right. I had suggested both but went with the latter because I could get it out quicker. Will send you a pull request for this later today.

Thanks
Sharan

**Comment by noirbizarre** [comment]
Can I close this PR as #103 should be fixed?

**Pull request closed without merging**
