### PR TITLE
Hide resource if doc is False

### PR DESCRIPTION
**Pull request by AleixDev**

### CODE REVIEW

**Comment by noirbizarre** [comment]
Hum, not sure what you are trying to achieve.
The current code state allow to write `@api.doc(False)` to ignore documentation.

Maybe I misunderstand but withtout details nor test, I can't merge this.

**Comment by AleixDev** [comment]
Yes it's working fine with:
`@api.doc(False)`

But I was trying to do this (as explained in the [documentation][1]):
`@api.route('/resource1/', doc=False)`

[1]: http://flask-restplus.readthedocs.org/en/stable/documenting.html#hiding-from-documentation

**Comment by noirbizarre** [comment]
OK, I just understood your PR. You are trying to do `@ns.route(doc=False)` which is not tested.
I was trying to figure out where you code came from because it's already implemented an api:
https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/api.py#L227

I cherry-picked your commit and added a test for it.

**Comment by AleixDev** [comment]
Yes, I'm using a namespace, not the root api. I forgot to mention it, thank you for taking the time to understand this PR :)

**Pull request closed without merging**
