### PR TITLE
Catch errors of child types

### PR DESCRIPTION
**Pull request by EdgyEdgemond**
Flask errorhandler catches subtypes of exceptions.

The restplus version only catches explicit errors, so if you have 50 errors all of base class MyException you need 50 api.errorhandler() decorations.

Not one api.errorhandler(MyException)

### CODE REVIEW

**Comment by noirbizarre** [comment]
Great improvement :ok_hand: but I need some tests and little explanation of this behavior somewhere in the documentation to be able to merge this PR

**Comment by EdgyEdgemond** [comment]
Tests and docs updated, shout out if you need more.

**Comment by noirbizarre** [comment]
Seems fine but your code base is outdated, can you rebase on the current master and resolve conflicts ?

**Comment by EdgyEdgemond** [comment]
Merge conflicts rectified.

**Pull request merged**
