### PR TITLE
Supporting a list of nested structures in swagger models.

### PR DESCRIPTION
**Pull request by slawekrewaj**
It probably fixes also https://github.com/noirbizarre/flask-restplus/issues/13.

### CODE REVIEW

**Comment by noirbizarre** [comment]
I won't merge this pull-request because I already implemented a fix in 09a6c64.
Thanks anyway.

Next time, try to add a test case.

**Comment by Liorinco** [comment]
Hi !

I didn't trie this with @api.marshal_with, so I don't know if it was corrected, but I found the same problem with @api.doc(body=MyModel).
When will it be corrected?

**Comment by noirbizarre** [comment]
It should already be corrected in 0.7.0.
What version are you using? Have you tested on 0.7.0 ?

**Comment by Liorinco** [comment]
Ok, I understand my mistake.
First, I'm a newbie on Github...
Second, I installed flask-resplus before your modifications and I forgot to download your last versions.
So I'm sorry about the trouble and I'll follow your banchs, continuing to enjoy your powerful modul.
Thank you !

**Comment by noirbizarre** [comment]
It's alright, don't worry :)
I hope this will fix your issue.

You're welcome and thanks for the pull-request anyway :)

**Comment by Liorinco** [comment]
Hi... the return!

I tested it and it works!
But I tried the same thing with body argument but it was not the result that I expected.

I tried:
MyModel = api.model('MyModel', {'id': fields.Integer, 'data'=fields.String})
@api.doc(body=[MyModel])

Expected result:
{[{
         'id': 0,
         'data': "string"
}]}

The result:
Array[#/definitions/MyModel]

Is it normal?

**Pull request closed without merging**
