### PR TITLE
Documenting using json schema

### PR DESCRIPTION
**Pull request by stevezau**
First pass at adding a SchemaModel for documenting using json schema

### CODE REVIEW

**Comment by stevezau** [comment]
hmm.. i tried to merge your changes in @gazpachoking but i wasn't sure what to do with __schema__ and schema as it looks like it has changed.

**Comment by stevezau** [comment]
@noirbizarre any feedback here?

**Comment by noirbizarre** [comment]
Very interesting ! I will take a closer look tonight :+1:

**Comment by stevezau** [comment]
Ah, I haven't looked at the tests yet. Was hoping for some feedback first.. :-)

**Comment by stevezau** [comment]
@noirbizarre tests are passing now, did you have a chance to take a look?

**Comment by stevezau** [comment]
Any update on this PR @noirbizarre ?

**Comment by stevezau** [comment]
@noirbizarre i'm not sure why travis failed, it looks like an unrelated issue to this PR..

Are you able to take a look now? Really want this merged in

**Comment by stevezau** [comment]
@noirbizarre added some docs.. pretty simple. How about a merge now?

**Comment by stevezau** [comment]
@noirbizarre any updates on this? It's been a while now :(

**Comment by garbas** [comment]
@stevezau could the same (json validation) be also done for the request parsing? /me new to flask-restplus

**Pull request merged**
