### PR TITLE
Add support for multiple parents in extend()

### PR DESCRIPTION
**Pull request by awiddersheim**

### CODE REVIEW

**Comment by awiddersheim** [comment]
Been using this and the other pull requests currently open for a few days now without any issues. Would love any feedback anyone might have. Also, it would be a huge help if these get merged and a new release gets pushed.

If there is anything I can do to help make that happen let me know.

**Comment by noirbizarre** [comment]
Hi !

Thanks for your pull-requests, these are interesting use cases.

I'm planning on performing a release this weekend and I already merged the others pull-request.

For this one to be merged, I'd like a test case illustrating the usage and ensuring that nominal and edge cases are working.

**Comment by awiddersheim** [comment]
Okay. I will see what I can come up with. I'd love to have this in the release you do so I'll try and put something together by tomorrow. It's a holiday weekend here in America but I hope to have something to you by then.

**Comment by noirbizarre** [comment]
No worries, I can wait until the beginning of the week to perform the release.
I'll wait for your completed pull-request.

Enjoy your holiday weekend ;)

**Comment by awiddersheim** [comment]
Worked on this now.

**Comment by awiddersheim** [comment]
Added some tests. Let me know if you'd like for me to do more than this.

**Comment by noirbizarre** [comment]
Great !

The test is fine, but I want to keep the existing one too. It ensure the old behavior is still working.
You should keep the ``test_extend`` untouched and write your test under a ``test_extend_with_multiple_parents`` by example.

After that, it's OK for merge.

**Comment by awiddersheim** [comment]
Alright, I think this is more a long the lines of what you wanted.

**Comment by awiddersheim** [comment]
Anyway we can get that release soon? Didn't mean to hold it up the last time.

**Pull request merged**
